
project_id = "tesvdaqrpynsrvkmfapw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
# Update the site URL to your deployment URL
site_url = "https://9f1d5b2d-925b-4ae7-9724-2e7d5f1c2dbc.lovableproject.com"
# Add redirect URLs for both local development and production
additional_redirect_urls = ["http://localhost:3000", "https://9f1d5b2d-925b-4ae7-9724-2e7d5f1c2dbc.lovableproject.com"]

[analytics]
enabled = false

[experimental]
enabled = false

# Desativar a verificação JWT para a função create-checkout
[functions.create-checkout]
verify_jwt = false

# Desativar a verificação JWT para a função verify-payment
[functions.verify-payment]
verify_jwt = false
