
project_id = "tesvdaqrpynsrvkmfapw"

[functions.increment_tickets_sold]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

