
project_id = "tesvdaqrpynsrvkmfapw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[experimental]
enabled = false

# Desativar a verificação JWT para a função create-checkout
[functions.create-checkout]
verify_jwt = false

# Desativar a verificação JWT para a função verify-payment
[functions.verify-payment]
verify_jwt = false
