// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tesvdaqrpynsrvkmfapw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlc3ZkYXFycHluc3J2a21mYXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODQ5MDgsImV4cCI6MjA2MDY2MDkwOH0.MVT6FOVsYjNwAqtOyHGKN6FCsXmhusiyXhtR3eb-SjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);